all: false
dir: '{{.InterfaceDir}}'
filename: mocks_test.go
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
recursive: false

packages:
  github.com/Vy4cheSlave/qna/internal/infrastructure/rest:
    interfaces:
      QNADispatcher:
    config:
      all: true
      dir: ./internal/infrastructure/rest/mocks
      filename: qna_dispatcher_mocks.go
      outpkg: mocks