// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/Vy4cheSlave/qna/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockQNADispatcher is an autogenerated mock type for the QNADispatcher type
type MockQNADispatcher struct {
	mock.Mock
}

type MockQNADispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQNADispatcher) EXPECT() *MockQNADispatcher_Expecter {
	return &MockQNADispatcher_Expecter{mock: &_m.Mock}
}

// CreateAnswerToQuestion provides a mock function with given fields: ctx, answer
func (_m *MockQNADispatcher) CreateAnswerToQuestion(ctx context.Context, answer *domain.Answer) (int, error) {
	ret := _m.Called(ctx, answer)

	if len(ret) == 0 {
		panic("no return value specified for CreateAnswerToQuestion")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Answer) (int, error)); ok {
		return rf(ctx, answer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Answer) int); ok {
		r0 = rf(ctx, answer)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Answer) error); ok {
		r1 = rf(ctx, answer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQNADispatcher_CreateAnswerToQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAnswerToQuestion'
type MockQNADispatcher_CreateAnswerToQuestion_Call struct {
	*mock.Call
}

// CreateAnswerToQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - answer *domain.Answer
func (_e *MockQNADispatcher_Expecter) CreateAnswerToQuestion(ctx interface{}, answer interface{}) *MockQNADispatcher_CreateAnswerToQuestion_Call {
	return &MockQNADispatcher_CreateAnswerToQuestion_Call{Call: _e.mock.On("CreateAnswerToQuestion", ctx, answer)}
}

func (_c *MockQNADispatcher_CreateAnswerToQuestion_Call) Run(run func(ctx context.Context, answer *domain.Answer)) *MockQNADispatcher_CreateAnswerToQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Answer))
	})
	return _c
}

func (_c *MockQNADispatcher_CreateAnswerToQuestion_Call) Return(answerId int, err error) *MockQNADispatcher_CreateAnswerToQuestion_Call {
	_c.Call.Return(answerId, err)
	return _c
}

func (_c *MockQNADispatcher_CreateAnswerToQuestion_Call) RunAndReturn(run func(context.Context, *domain.Answer) (int, error)) *MockQNADispatcher_CreateAnswerToQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateQuestion provides a mock function with given fields: ctx, question
func (_m *MockQNADispatcher) CreateQuestion(ctx context.Context, question *string) (int, error) {
	ret := _m.Called(ctx, question)

	if len(ret) == 0 {
		panic("no return value specified for CreateQuestion")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) (int, error)); ok {
		return rf(ctx, question)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string) int); ok {
		r0 = rf(ctx, question)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, question)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQNADispatcher_CreateQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQuestion'
type MockQNADispatcher_CreateQuestion_Call struct {
	*mock.Call
}

// CreateQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - question *string
func (_e *MockQNADispatcher_Expecter) CreateQuestion(ctx interface{}, question interface{}) *MockQNADispatcher_CreateQuestion_Call {
	return &MockQNADispatcher_CreateQuestion_Call{Call: _e.mock.On("CreateQuestion", ctx, question)}
}

func (_c *MockQNADispatcher_CreateQuestion_Call) Run(run func(ctx context.Context, question *string)) *MockQNADispatcher_CreateQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string))
	})
	return _c
}

func (_c *MockQNADispatcher_CreateQuestion_Call) Return(questionId int, err error) *MockQNADispatcher_CreateQuestion_Call {
	_c.Call.Return(questionId, err)
	return _c
}

func (_c *MockQNADispatcher_CreateQuestion_Call) RunAndReturn(run func(context.Context, *string) (int, error)) *MockQNADispatcher_CreateQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, userName
func (_m *MockQNADispatcher) CreateUser(ctx context.Context, userName *string) (*string, error) {
	ret := _m.Called(ctx, userName)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) (*string, error)); ok {
		return rf(ctx, userName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string) *string); ok {
		r0 = rf(ctx, userName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, userName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQNADispatcher_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockQNADispatcher_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userName *string
func (_e *MockQNADispatcher_Expecter) CreateUser(ctx interface{}, userName interface{}) *MockQNADispatcher_CreateUser_Call {
	return &MockQNADispatcher_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, userName)}
}

func (_c *MockQNADispatcher_CreateUser_Call) Run(run func(ctx context.Context, userName *string)) *MockQNADispatcher_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string))
	})
	return _c
}

func (_c *MockQNADispatcher_CreateUser_Call) Return(userId *string, err error) *MockQNADispatcher_CreateUser_Call {
	_c.Call.Return(userId, err)
	return _c
}

func (_c *MockQNADispatcher_CreateUser_Call) RunAndReturn(run func(context.Context, *string) (*string, error)) *MockQNADispatcher_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAnswer provides a mock function with given fields: ctx, answerId
func (_m *MockQNADispatcher) DeleteAnswer(ctx context.Context, answerId int) error {
	ret := _m.Called(ctx, answerId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAnswer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, answerId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQNADispatcher_DeleteAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAnswer'
type MockQNADispatcher_DeleteAnswer_Call struct {
	*mock.Call
}

// DeleteAnswer is a helper method to define mock.On call
//   - ctx context.Context
//   - answerId int
func (_e *MockQNADispatcher_Expecter) DeleteAnswer(ctx interface{}, answerId interface{}) *MockQNADispatcher_DeleteAnswer_Call {
	return &MockQNADispatcher_DeleteAnswer_Call{Call: _e.mock.On("DeleteAnswer", ctx, answerId)}
}

func (_c *MockQNADispatcher_DeleteAnswer_Call) Run(run func(ctx context.Context, answerId int)) *MockQNADispatcher_DeleteAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockQNADispatcher_DeleteAnswer_Call) Return(_a0 error) *MockQNADispatcher_DeleteAnswer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQNADispatcher_DeleteAnswer_Call) RunAndReturn(run func(context.Context, int) error) *MockQNADispatcher_DeleteAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQuestionAndAnswers provides a mock function with given fields: ctx, questionId
func (_m *MockQNADispatcher) DeleteQuestionAndAnswers(ctx context.Context, questionId int) error {
	ret := _m.Called(ctx, questionId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQuestionAndAnswers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, questionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQNADispatcher_DeleteQuestionAndAnswers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQuestionAndAnswers'
type MockQNADispatcher_DeleteQuestionAndAnswers_Call struct {
	*mock.Call
}

// DeleteQuestionAndAnswers is a helper method to define mock.On call
//   - ctx context.Context
//   - questionId int
func (_e *MockQNADispatcher_Expecter) DeleteQuestionAndAnswers(ctx interface{}, questionId interface{}) *MockQNADispatcher_DeleteQuestionAndAnswers_Call {
	return &MockQNADispatcher_DeleteQuestionAndAnswers_Call{Call: _e.mock.On("DeleteQuestionAndAnswers", ctx, questionId)}
}

func (_c *MockQNADispatcher_DeleteQuestionAndAnswers_Call) Run(run func(ctx context.Context, questionId int)) *MockQNADispatcher_DeleteQuestionAndAnswers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockQNADispatcher_DeleteQuestionAndAnswers_Call) Return(_a0 error) *MockQNADispatcher_DeleteQuestionAndAnswers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQNADispatcher_DeleteQuestionAndAnswers_Call) RunAndReturn(run func(context.Context, int) error) *MockQNADispatcher_DeleteQuestionAndAnswers_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, userId
func (_m *MockQNADispatcher) DeleteUser(ctx context.Context, userId *string) error {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) error); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQNADispatcher_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockQNADispatcher_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userId *string
func (_e *MockQNADispatcher_Expecter) DeleteUser(ctx interface{}, userId interface{}) *MockQNADispatcher_DeleteUser_Call {
	return &MockQNADispatcher_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, userId)}
}

func (_c *MockQNADispatcher_DeleteUser_Call) Run(run func(ctx context.Context, userId *string)) *MockQNADispatcher_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*string))
	})
	return _c
}

func (_c *MockQNADispatcher_DeleteUser_Call) Return(_a0 error) *MockQNADispatcher_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQNADispatcher_DeleteUser_Call) RunAndReturn(run func(context.Context, *string) error) *MockQNADispatcher_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetAnswer provides a mock function with given fields: ctx, answerId
func (_m *MockQNADispatcher) GetAnswer(ctx context.Context, answerId int) (*domain.Answer, error) {
	ret := _m.Called(ctx, answerId)

	if len(ret) == 0 {
		panic("no return value specified for GetAnswer")
	}

	var r0 *domain.Answer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Answer, error)); ok {
		return rf(ctx, answerId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Answer); ok {
		r0 = rf(ctx, answerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Answer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, answerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQNADispatcher_GetAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAnswer'
type MockQNADispatcher_GetAnswer_Call struct {
	*mock.Call
}

// GetAnswer is a helper method to define mock.On call
//   - ctx context.Context
//   - answerId int
func (_e *MockQNADispatcher_Expecter) GetAnswer(ctx interface{}, answerId interface{}) *MockQNADispatcher_GetAnswer_Call {
	return &MockQNADispatcher_GetAnswer_Call{Call: _e.mock.On("GetAnswer", ctx, answerId)}
}

func (_c *MockQNADispatcher_GetAnswer_Call) Run(run func(ctx context.Context, answerId int)) *MockQNADispatcher_GetAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockQNADispatcher_GetAnswer_Call) Return(_a0 *domain.Answer, _a1 error) *MockQNADispatcher_GetAnswer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQNADispatcher_GetAnswer_Call) RunAndReturn(run func(context.Context, int) (*domain.Answer, error)) *MockQNADispatcher_GetAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuestionAndAnswers provides a mock function with given fields: ctx, questionId
func (_m *MockQNADispatcher) GetQuestionAndAnswers(ctx context.Context, questionId int) (*domain.Question, *[]domain.Answer, error) {
	ret := _m.Called(ctx, questionId)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionAndAnswers")
	}

	var r0 *domain.Question
	var r1 *[]domain.Answer
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Question, *[]domain.Answer, error)); ok {
		return rf(ctx, questionId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Question); ok {
		r0 = rf(ctx, questionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) *[]domain.Answer); ok {
		r1 = rf(ctx, questionId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*[]domain.Answer)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = rf(ctx, questionId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockQNADispatcher_GetQuestionAndAnswers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuestionAndAnswers'
type MockQNADispatcher_GetQuestionAndAnswers_Call struct {
	*mock.Call
}

// GetQuestionAndAnswers is a helper method to define mock.On call
//   - ctx context.Context
//   - questionId int
func (_e *MockQNADispatcher_Expecter) GetQuestionAndAnswers(ctx interface{}, questionId interface{}) *MockQNADispatcher_GetQuestionAndAnswers_Call {
	return &MockQNADispatcher_GetQuestionAndAnswers_Call{Call: _e.mock.On("GetQuestionAndAnswers", ctx, questionId)}
}

func (_c *MockQNADispatcher_GetQuestionAndAnswers_Call) Run(run func(ctx context.Context, questionId int)) *MockQNADispatcher_GetQuestionAndAnswers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockQNADispatcher_GetQuestionAndAnswers_Call) Return(_a0 *domain.Question, _a1 *[]domain.Answer, _a2 error) *MockQNADispatcher_GetQuestionAndAnswers_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockQNADispatcher_GetQuestionAndAnswers_Call) RunAndReturn(run func(context.Context, int) (*domain.Question, *[]domain.Answer, error)) *MockQNADispatcher_GetQuestionAndAnswers_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuestions provides a mock function with given fields: ctx
func (_m *MockQNADispatcher) GetQuestions(ctx context.Context) (*[]domain.Question, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestions")
	}

	var r0 *[]domain.Question
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]domain.Question, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]domain.Question); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.Question)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQNADispatcher_GetQuestions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuestions'
type MockQNADispatcher_GetQuestions_Call struct {
	*mock.Call
}

// GetQuestions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQNADispatcher_Expecter) GetQuestions(ctx interface{}) *MockQNADispatcher_GetQuestions_Call {
	return &MockQNADispatcher_GetQuestions_Call{Call: _e.mock.On("GetQuestions", ctx)}
}

func (_c *MockQNADispatcher_GetQuestions_Call) Run(run func(ctx context.Context)) *MockQNADispatcher_GetQuestions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQNADispatcher_GetQuestions_Call) Return(_a0 *[]domain.Question, _a1 error) *MockQNADispatcher_GetQuestions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQNADispatcher_GetQuestions_Call) RunAndReturn(run func(context.Context) (*[]domain.Question, error)) *MockQNADispatcher_GetQuestions_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: ctx
func (_m *MockQNADispatcher) GetUsers(ctx context.Context) (*[]domain.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 *[]domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*[]domain.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *[]domain.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQNADispatcher_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockQNADispatcher_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQNADispatcher_Expecter) GetUsers(ctx interface{}) *MockQNADispatcher_GetUsers_Call {
	return &MockQNADispatcher_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx)}
}

func (_c *MockQNADispatcher_GetUsers_Call) Run(run func(ctx context.Context)) *MockQNADispatcher_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQNADispatcher_GetUsers_Call) Return(_a0 *[]domain.User, _a1 error) *MockQNADispatcher_GetUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQNADispatcher_GetUsers_Call) RunAndReturn(run func(context.Context) (*[]domain.User, error)) *MockQNADispatcher_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQNADispatcher creates a new instance of MockQNADispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQNADispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQNADispatcher {
	mock := &MockQNADispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
